services:
    sonata.admin.post:
        class: Acme\DemoBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Add Post" }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]


    sonata.admin.users:
        class: Acme\DemoBundle\Admin\UsersAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Add User" }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\Users
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]